ctf-wiki/ctf-wiki

requirements.txt

mkdocs v1.0 was released hours ago. With the URL schema refactored, it is not compatible with current mkdocs-material version.
FYI: https://github.com/squidfunk/mkdocs-material/issues/834
(reproduced in my own repo)

fix: fix mkdocs version here temporarily

---

docs/crypto/asymmetric/discrete-log/discrete-log.md
mkdocs.yml

该文章犯了两个原则性错误：
1. 整数集和四则运算不构成域，作为标题这很令人尴尬。
2. 关于原根的 “性质 1” 不存在。一对反例： 3 和 1 ，另一对非平凡反例： 7 和 2 。顺便一提，求原根也是一个难解问题。
原文中的 “性质 3” 不应作为性质存在，未修改。
重新组织某些语句，使之更通顺自然。
改善了部分数学公式代码。
提供了 baby-step giant-step 算法的 Python 实现。

修正一些错误以及提供了 BSGS 的 Python 实现

---

docs/misc/traffic/data.md

在misc的流量分析一节中加入hitcon 2018 ev3例题，用以解释自定义协议的分析方法。
有两道同系列的题目，仅提供了第一道的详细方法，第二道难度更大的可作为读者练习。因为作为示例，第一题的方法解释已经足够清楚，提供第二题的wp可能使内容冗赘。
题目本身指向ctftime，不确定这个题能不能直接上传到ctf-challenges？

Add HITCON 2018 ev3 example in misc

---

Dockerfile
README.md

ATT.
Just build and serve using lighttpd. Still need to change CDN resource to local. Please create a new issue for me if accepted.
And I also created a docker hub organization called ctfwiki (hyphen is not allowed by docker hub), more member need to be added.
`docker run -d xm1994/ctf-wiki:add-dockerfile` and will run it now.

A very initial Dockerfile to view ctf-wiki at local.

---

docs/pwn/linux/glibc-heap/heap_overview.md

这里指向的链接是 `malloc.c` 但是原来是 `maloc.h`。。我改了这一小处。

fix a small bug

---

docs/pwn/linux/kernel/kernel_uaf.md

fix #516 
slub分配时，0x8a和0xab 都在128-256这一块slab

fix wrong struct size in kernel_uaf

---

README-zh_CN.md
README.md

fix git clone link to using https protocol, instead of git protocol

fix git clone link

---

docs/crypto/asymmetric/discrete-log/ecc.md
docs/pwn/linux/glibc-heap/tcache_attack-zh.md
docs/pwn/linux/io_file/exploit-in-libc2.24-zh.md
docs/pwn/linux/io_file/exploit-in-libc2.24.md
docs/reverse/windows/anti-debug/checkremotedebuggerpresent-zh.md
docs/reverse/windows/anti-debug/example-zh.md
docs/reverse/windows/anti-debug/example.md
mkdocs.yml

I found some link errors in document and fix it.
Here is the list of errors fixed.
```
FIXED -  A relative path to 'crypto/asymmetric/discrete-log/ecc-zh' is included in the 'nav' configuration, which is not found in the documentation files
FIXED -  Documentation file 'pwn\linux\glibc-heap\tcache_attack-zh.md' contains a link to 'pwn\linux\glibc-heap\unlink.md' which is not found in the documentation files.
FIXED -  Documentation file 'pwn\linux\io_file\exploit-in-libc2.24.md' contains a link to 'pwn\linux\io_file\exploit-in-libc2.md' which is not found in the documentation files.
FIXED -  Documentation file 'pwn\linux\io_file\exploit-in-libc2.24.md' contains a link to 'pwn\linux\io_file\exploit-in-libc2-zh.md' which is not found in the documentation files.
FIXED -  Documentation file …
```

Fix some link error

---

docs/android/basic_operating_mechanism/java_layer/dex/dex.md

Additional newline in the data type and file header tables causes its contents to be shown as raw text rather than table contents

Removed newlines from tables

---

mkdocs-zh.yml
mkdocs.yml

Fix the bug reported in https://github.com/ctf-wiki/ctf-wiki/issues/618#issuecomment-615434077 (that `mkdocs build` fails with `mkdocs-material >= v5.0` )
Closes #618 (possibly)
This commit changes both the `mkdocs.yml` and `mkdocs-zh.yml`
The changes are made following the guidance of https://squidfunk.github.io/mkdocs-material/releases/5/#how-to-upgrade

Upgrading mkdocs material theme to v5.0

---

docs/crypto/asymmetric/lattice/lattice-reduction-zh.md
docs/crypto/asymmetric/lattice/lattice-reduction.md
docs/crypto/asymmetric/rsa/rsa_coppersmith_attack-zh.md
docs/crypto/blockcipher/aes-zh.md
docs/crypto/blockcipher/des-zh.md
docs/crypto/blockcipher/des.md
docs/executable/elf/elf-structure-zh.md
docs/executable/elf/program-linking-zh.md
docs/executable/elf/program-linking.md
docs/introduction/mode-zh.md
docs/introduction/mode.md
docs/misc/encode/computer-zh.md
docs/misc/encode/computer.md
docs/pwn/linux/glibc-heap/fastbin_attack-zh.md
docs/pwn/linux/glibc-heap/heap_overview-zh.md
docs/pwn/linux/glibc-heap/heap_overview.md
docs/pwn/linux/glibc-heap/house_of_einherjar-zh.md
docs/pwn/linux/glibc-heap/house_of_einherjar.md
docs/pwn/linux/glibc-heap/unlink-zh.md
docs/pwn/linux/glibc-heap/unsorted_bin_attack-zh.md
docs/pwn/linux/glibc-heap/unsorted_bin_attack.md
docs/pwn/linux/integeroverflow/intof-zh.md
docs/pwn/linux/integeroverflow/intof.md
docs/pwn/linux/race-condition/introduction-zh.md
docs/pwn/linux/race-condition/introduction.md
docs/pwn/linux/sandbox/python-sandbox-escape-zh.md
docs/pwn/linux/sandbox/python-sandbox-escape.md
docs/reverse/Identify-Encode-Encryption/introduction-zh.md
docs/reverse/Identify-Encode-Encryption/introduction.md

Fixes #673
This commit searches and removes all `typora-root-url` entries in the `.md` files
It aims to remove the unwanted header at the top of each document

Remove unwanted typora-root-url

---

docs/crypto/asymmetric/rsa/rsa_theory-zh.md
docs/crypto/asymmetric/rsa/rsa_theory.md

修复 RSA 介绍 中的 typo

---

docs/_static/js/extra.js
docs/index-en.md
docs/index.md
mkdocs-zh.yml
mkdocs.yml

添加了暗色模式（mkdocs-material新特性）
~~已有问题：颜色button无法显示对应的主题色，参考[demo](https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme)。18年的[ctfwiki镜像](https://wiki.x10sec.org/#material-color-palette)没有这个问题，应该是mkdocs-material的版本差异。~~ fixed

Feature: add dark mode support

---

docs/pwn/linux/stackoverflow/medium-rop.md

Fixed some errors in the Markdown that caused most of the medium-rop page to be rendered as a code block

Fixed Markdown syntax issues

---

docs/web/introduction.md

* The extra before `js prevented proper rendering of code in rest of the page.
* Fixed it removing the space.

fix extra space in code block

---

docs/misc/audio/introduction-zh.md
docs/misc/audio/introduction.md

Minor Typo Fix: 
- in docs/misc/audio/introduction-zh.md and
docs/misc/audio/introduction.md
The tool name is silenteye, not 'slienteye'

Minor Typo Fix in docs/misc/audio

---

docs/pwn/linux/kernel/double-fetch.md

docs/pwn/linux/kernel/double-fetch.md
`- [Typical Double Fetch Schematic] (./double-fetch.png)`
`+ [Typical Double Fetch Schematic](./double-fetch.png)`

fix broken png link

---

docs/zh/docs/pwn/linux/glibc-heap/implementation/tcache.md
docs/zh/docs/pwn/linux/glibc-heap/tcache_attack.md

It should be `tcache_perthread_struct` instead of `tcache_prethread_struct`.

fix typo in tcache implementation page

---

README.md

An a tag is not closed, causing the following content to display abnormally.

fix a bug in README

---

docs/zh/docs/pwn/linux/kernel-mode/environment/qemu-emulate.md

After `make`, busybox only generates the binary, without construct `_install` directory.
After `make install`, `_install` is generated.
Maybe the author forgets this command.

Add missing command before constructing `_install`

---

docs/zh/docs/crypto/asymmetric/rsa/rsa_module_attack.md

In pollard's p-1 smooth code, q should be divided by N, not n
**Before submitting this pull request, please read**
- [Contribute](https://ctf-wiki.org/contribute/before-contributing/)
**Please remove these message before PR.**

fix one typo

---

docs/zh/docs/usage.md

- `rop`的超链接 404
- `基本 ROP`书写不规范
- 题目的超链接没有被标识为超链接，导致部分浏览器认为`。`是链接的一部分

修复《如何使用》章节中的一些 bug

---

docs/zh/docs/misc/archive/rar.md

The original link is moved to the new one.

fix: invalid links in rar.md

---

docs/zh/docs/crypto/classical/polyalphabetic.md

明文：come greatwall
密钥：cryp tocryptoc
密文：efkt zfgrrltzn
e+c->g

维吉尼亚密码示例密文错误

---

docs/zh/docs/pwn/linux/kernel-mode/environment/qemu-emulate.md

在搭建内核运行环境的编译 BusyBox文档中 https://ctf-wiki.org/pwn/linux/kernel-mode/environment/qemu-emulate/#busybox_3
有两处错误非常致命，会导致编译的busybox无法使用。
具体的文件在 docs/zh/docs/pwn/linux/kernel-mode/environment/qemu-emulate.md 中
将 “在我们创建的 ./etc/inttab 中写入如下内容：” 改成 “在我们创建的 ./etc/inittab 中写入如下内容：”。也就是将./etc/inttab 改成 ./etc/inittab
将 ::askfirst:/bin/ash 改成 ::askfirst:/bin/sh

fix spelling errors for https://github.com/ctf-wiki/ctf-wiki/issues/949
