- crypto/asymmetric/rsa/example/2016-HCTF-RSA2/rsa2.py
> import time

- web/php.md
> [GitHacker](https://github.com/WangYihang/GitHacker.git)
> 添加 Git 源码泄露利用工具

- pwn/stackoverflow/basic_rop.md
- pwn/stackoverflow/basic_rop.rst
看基本ROP的时候找题目下载花了一些时间，所以添加题目下载地址上去
>  基本ROP添加例子下载地址

- reverse/anti_debug/example.rst
- reverse/anti_debug/index.rst
- reverse/anti_debug/junk_code.rst
- reverse/anti_debug/ntglobalflag.rst
- reverse/linux/detect_bp.md
- reverse/linux/detect_bp.rst
- reverse/linux/detect_dbg.md
- reverse/linux/detect_dbg.rst
- reverse/linux/false_disasm.md
- reverse/linux/false_disasm.rst
- reverse/linux/index.rst
- reverse/linux/ld_preload.rst
- reverse/unicorn/index.rst
- reverse/unpack/direct_oep.rst
- reverse/unpack/esp.rst
- reverse/unpack/fix_iat.md
- reverse/unpack/fix_iat.rst
- reverse/unpack/index.rst
- reverse/unpack/last_exception.rst
- reverse/unpack/manually_fix_iat.md
- reverse/unpack/manually_fix_iat.rst
- reverse/unpack/memory.rst
- reverse/unpack/sfx.rst
- reverse/unpack/trace.rst
- reverse/unpack/unpack_dll.md
- reverse/unpack/unpack_dll.rst
1. add:
- reverse/linux/detect_bp.md
- reverse/linux/detect_dbg.md
-  reverse/linux/false_disasm.md
2. delete:
- additional image names in all rst files
> remove some rubbish and add anti-disasm tricks.

- docs/pwn/io_file/introduction.md
Too small to open a pull request
> Fix small spelling mistake

- docs/pwn/stackoverflow/stackoverflow_basic.md
test environments: gcc version 7.2.0
> Add -no-pie option

- docs/pwn/heap/House of Rabbit.md
> add house of rabbit

- docs/pwn/heap/house_of_einherjar.md
> add some example code to House Of Einherjar

- docs/pwn/heap/house_of_lore.md
add some code for the  house of lore.
> add example code for house of lore

- docs/pwn/heap/unsorted_bin_attack.md
> fix shellfish 2 shellphish

- docs/crypto/classical/summary.md
Thank you for contributing to CTF Wiki!
> 一个简单题目的更优解法

- docs/pwn/readme.md
- docs/reverse/Identify-Encode-Encryption/introduction.md
> add some reverse and pwn readme

- docs/assembly/mips/readme.md
> add MIPS Instruction and Registers

- docs/assembly/mips/readme.md
>  修复下 错误的公式表示

- docs/pwn/linux/fmtstr/fmtstr_example.md
> correct exp and description of fmt-heap challenges

- docs/pwn/linux/heap/off_by_one.md
> add samples full exp of challenge books

- docs/crypto/asymmetric/rsa/rsa_complex.md
> add challenge "Tokyo Western 2018 Mixed Cipher" to rsa complex

- docs/web/php/php.md
> fix https://github.com/ctf-wiki/comment/issues/33

- docs/pwn/linux/io_file/fake-vtable-exploit.md
> 添加了一个IO_file分类下 伪造vtables的例题

- docs/pwn/linux/glibc-heap/tcache_attack.md
> update tcache double free check

- docs/web/sqli.md
> add dnslog injection

- docs/pwn/linux/stackoverflow/basic-rop.md
> fixed repeat quotation marks

- docs/pwn/linux/glibc-heap/unsorted_bin_attack.md
> add remove from unsorted list source code

- docs/pwn/linux/io_file/exploit-in-libc2.24.md
>  modify in glibc 2.24 io-file exploit

- docs/pwn/linux/io_file/exploit-in-libc2.24.md
> add _IO_str_finish to bypass vtable check

- mkdocs.yml
> modify name of glibc 2.24

- docs/pwn/linux/glibc-heap/tcache_attack.md
> reconstruction of pwn/linux/glibc_heap/tcache_attack

- mkdocs.yml
> reconsitution directory

- docs/crypto/asymmetric/lattice/lattice-reduction.md
Minor fixes for incorrect figure paths inside lattice-reduction.md.
> Fix lattice-reduction.md figure path

- docs/pwn/linux/glibc-heap/large_bin_attack.md
- docs/pwn/linux/io_file/exploit-in-libc2.24.md
- mkdocs.yml
> add largebin attack

- mkdocs.yml
> fix mkdocs.yml

- docs/crypto/asymmetric/lattice/lattice-reduction.md
> fix figure path

- mkdocs.yml
Fixed allignment in the yml definition of the english->zh translations
> fixed some allignment in the tabs of pwn

- docs/crypto/asymmetric/lattice/cvp.md
- docs/crypto/asymmetric/lattice/introduction.md
- docs/crypto/asymmetric/lattice/lattice-reduction.md
- docs/crypto/asymmetric/lattice/overview.md
- docs/crypto/hash/fnv.md
- mkdocs.yml
This fixes numerous translation errors in the Lattice based cryptography section.
> Fix translations for Lattice-based Crypto

- docs/web/php/php-zh.md
- docs/web/php/php.md
> php grammar error repair

- docs/pwn/linux/kernel/basic_knowledge-zh.md
- docs/pwn/linux/kernel/basic_knowledge.md
Add slashes to make sure \* display properly in markdown.
> Fix display issue of *

- docs/web/sqli-zh.md
- docs/web/sqli.md
> fix #572 修复失效链接

- docs/pwn/windows/stackoverflow/stack-introduce-zh.md
- docs/pwn/windows/stackoverflow/stack-introduce.md
- docs/pwn/windows/stackoverflow/stackoverflow-basic-zh.md
- docs/pwn/windows/stackoverflow/stackoverflow-basic.md
> fix error url

- docs/assembly/mips/readme-zh.md
Modify mips zh page.
英文页面由于排版问题所有的表格都有问题，我会重新提一个pr修复一下，并更正其中的错误的代码（参考[MIPS Instruction Reference](http://www.mrc.uidaho.edu/mrc/people/jff/digital/MIPSir.html)）
> Update mips readme-zh.md

- docs/assembly/mips/readme.md
Modify mips page and correct some encoding codes.Add a reference link.
> Update mips readme.md

- docs/crypto/blockcipher/introduction.md
- docs/index-en.md
- mkdocs.yml
> Index En-translation Fix

- docs/pwn/linux/glibc-heap/house_of_einherjar.md
Copied from <https://github.com/ctf-wiki/ctf-challenges/blob/master/pwn/heap/house-of-einherjar/2016_seccon_tinypad/exp.py>.
> chore: fix copy pasta errors

- docs/pwn/linux/kernel/basic_knowledge-zh.md
> 添加64 syscall table链接

- docs/pwn/linux/glibc-heap/heap_structure-zh.md
- docs/pwn/linux/glibc-heap/heap_structure.md
Just a clerical error: change `MORECODE` to `MORECORE`.
Thanks!
> fix a clerical error

- docs/pwn/linux/glibc-heap/heap_structure-zh.md
- docs/pwn/linux/glibc-heap/heap_structure.md
- docs/pwn/linux/glibc-heap/implementation/basic-zh.md
- docs/pwn/linux/glibc-heap/implementation/basic.md
Just a little minor writing issues.
Thanks!
> fix some minor writing issues

- docs/pwn/linux/mitigation/canary-zh.md
> 修正canary不同thread不一样的说法(ZH)

- docs/pwn/linux/mitigation/canary.md
> 修正canary不同thread不一样的说法(EN)

- docs/pwn/linux/glibc-heap/implementation/malloc-zh.md
- docs/pwn/linux/glibc-heap/implementation/malloc.md
Fix some minor writing issues. Also, it seems there are more code format issues with English docs.
So just fix part of format issues now. Maybe more later.
> fix minor writing issues

- docs/pwn/linux/glibc-heap/implementation/malloc.md
fix the remaining code format issue in malloc.md
> correct code format of malloc doc

- docs/misc/archive/rar.md
fix lay out problem in misc/archive/rar.md
> fix layout problem

- docs/pwn/linux/glibc-heap/house_of_lore-zh.md
- docs/pwn/linux/glibc-heap/house_of_lore.md
just a few writing issues in house_of_lore doc
> fix writing issues in house_of_lore doc

- docs/crypto/hash/complex-zh.md
> increase a challenge of hash

- docs/pwn/linux/glibc-heap/house_of_orange-zh.md
- docs/pwn/linux/glibc-heap/house_of_orange.md
just a few format issues in house_of_orange doc
> fix format issues

- docs/pwn/linux/glibc-heap/house_of_orange-zh.md
- docs/pwn/linux/glibc-heap/house_of_orange.md
- docs/pwn/linux/glibc-heap/house_of_roman-zh.md
- docs/pwn/linux/glibc-heap/house_of_roman.md
just a few format issues again
> fix some format issues

- mkdocs-zh.yml
- mkdocs.yml
> Happy New Year！！！

- docs/crypto/asymmetric/rsa/rsa_theory-zh.md
- docs/crypto/asymmetric/rsa/rsa_theory.md
might still have some problems
> fix some mathjax problems

- docs/reverse/windows/anti-debug/zwsetinformationthread-zh.md
- docs/reverse/windows/anti-debug/zwsetinformationthread.md
- mkdocs-zh.yml
- mkdocs.yml
> add windows anti debug ZwSetInformationThread

- docs/pwn/linux/glibc-heap/tcache_attack-zh.md
I've corrected some syntax error in the article commited before. Thank you guys for such awsome work. Ctf-wiki is where I start my pwn skills learning. I am really happy to make a little contribution to it :)
> Tcache stashing unlink attck branch

- docs/crypto/certificate/introduction.md
The original writing was not quite rigorous. I modified the descriptions and added some Python examples.
> Rewrite "Certificate Format" Chapter - EN version

- docs/zh/docs/misc/archive/rar.md
The link with details is outdated and can not be opened, so I replace with a new link.
> Update the link with details

- docs/en/mkdocs.yml
- docs/zh/mkdocs.yml
> Fix edit URI

- docs/zh/docs/blockchain/ethereum/challenges.md
update challenges.md in blockchain
> 20210313 commit: update challenges.md in blockchain

- docs/zh/docs/contribute/basic-contribute-approach.md
> Fix outdated ref link in  basic-contribute-approach

- docs/zh/docs/blockchain/ethereum/attacks/arbitrarywrite.md
- docs/zh/docs/blockchain/ethereum/attacks/delegatecall.md
- docs/zh/docs/blockchain/ethereum/challenges.md
> 20210314 commit: update blockchain articles

- docs/zh/docs/blockchain/ethereum/attacks/arbitrarywrite.md
- docs/zh/docs/blockchain/ethereum/attacks/delegatecall.md
update some mistakes of blockchain article
> 20210314 commit: update some mistakes of blockchain article

- docs/zh/docs/introduction/resources.md
> 添加CTFHub，删除失效链接

- docs/zh/docs/web/introduction.md
Add introduction to HTTP request smuggling.
> add request smuggling in intro

- docs/en/docs/index.md
- docs/en/mkdocs.yml
- docs/zh/docs/index.md
- docs/zh/docs/usage.md
- docs/zh/mkdocs.yml
> add usage of ctf-wiki

- docs/zh/docs/introduction/resources.md
Added some navigation stations
> Added some navigation stations

- docs/zh/docs/web/introduction.md
Add(web): Add TLS Poison in introduction
> Add(web): Add TLS Poison in introduction

- docs/zh/docs/crypto/asymmetric/rsa/rsa_module_attack.md
Added detailed principles of williams p+1 smooth attack。XD
> Updated the detailed principle of p+1 smooth attack in RSA in the CRYPTO

- docs/zh/docs/crypto/asymmetric/rsa/rsa_module_attack.md
Added detailed principles of Pollard's p-1 smooth attack.XD
> Updated the detailed principle of p-1 smooth attack in RSA

- docs/zh/docs/blockchain/introduction.md
- docs/zh/mkdocs.yml
BlockChain->Blockchain
ref: https://en.wikipedia.org/wiki/Blockchain
> convert letter case of BlockChain

- docs/zh/docs/reverse/identify-encode-encryption/introduction.md
use more accurate wording (#821)
> use more accurate wording (#821)

- docs/zh/docs/pwn/linux/kernel-mode/environment/qemu-emulate.md
This link points it out.
https://kiprey.gitee.io/2021/10/kernel_pwn_introduction/
> Fix a typo of qemu-emulate.md

- docs/zh/docs/misc/picture/gif.md
Fix https://github.com/ctf-wiki/ctf-wiki/issues/845
Change language to console according to https://pygments.org/languages/
> fix markdown syntax in gif.md

- docs/zh/docs/pwn/windows/stackoverflow/stackoverflow-basic.md
fix issue of #862 need a <string.h> declaration to correctly compile.
> fix issue of #862 need a <string.h> declaration

- docs/zh/docs/pwn/linux/user-mode/heap/ptmalloc2/heap-structure.md
> heap-structure.md: 加一段对bins数组的描述

- docs/zh/docs/pwn/linux/user-mode/heap/ptmalloc2/use-after-free.md
**Before submitting this pull request, please read**
- [Contribute](https://ctf-wiki.org/contribute/before-contributing/)
**Please remove these message before PR.**
> 修正use after free 章节中，HITCON-training  lab 10 hacknote 例题的描述错误

- docs/zh/docs/crypto/asymmetric/lattice/lattice-reduction.md
带入i=1为2n
**Before submitting this pull request, please read**
- [Contribute](https://ctf-wiki.org/contribute/before-contributing/)
**Please remove these message before PR.**
> fix (lattice/lattice-reduction.md): 修一个公式错误

- docs/zh/docs/reverse/platform/windows/unpack/direct-oep.md
- docs/zh/docs/reverse/platform/windows/unpack/esp.md
- docs/zh/docs/reverse/platform/windows/unpack/last-exception.md
- docs/zh/docs/reverse/platform/windows/unpack/manually-fix-iat.md
- docs/zh/docs/reverse/platform/windows/unpack/memory.md
- docs/zh/docs/reverse/platform/windows/unpack/sfx.md
- docs/zh/docs/reverse/platform/windows/unpack/trace.md
- docs/zh/docs/reverse/platform/windows/unpack/unpack-dll.md
> fix_unpack_error_url

- README-zh_CN.md
- README.md
> Change opencollective to contributors-img

- docs/zh/docs/pwn/linux/kernel-mode/environment/qemu-emulate.md
> add qemu-kgdb environment

- docs/zh/docs/pwn/linux/kernel-mode/basic-knowledge.md
- docs/zh/docs/pwn/linux/kernel-mode/environment/qemu-emulate.md
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/heap/buddy/page-uaf.md
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/introduction.md
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/rop/ret2ptregs.md
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/rop/rop.md
- docs/zh/mkdocs.yml
Add:
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/introduction.md
Updates:
- docs/zh/docs/pwn/linux/kernel-mode/basic-knowledge.md
- docs/zh/docs/pwn/linux/kernel-mode/environment/qemu-emulate.md
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/heap/buddy/page-uaf.md
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/rop/ret2ptregs.md
- docs/zh/docs/pwn/linux/kernel-mode/exploitation/rop/rop.md
arttnba3 @ CTF-Wiki team
2025/04/02
> Several updates for linux kernel pwn
